import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Locale = "en" | "fr" | "ar";

type TranslationMap = Record<string, string>;

const translations: Record<Locale, TranslationMap> = {
  en: {
    "language.label": "Language",
    "language.select": "Select language",
    "language.en": "English",
    "language.fr": "Français",
    "language.ar": "العربية",
    "theme.switchToDark": "Switch to dark mode",
    "theme.switchToLight": "Switch to light mode",
    "brand.role": "AI & Data Science Engineer",
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.education": "Education",
    "nav.contact": "Contact",
    "header.download": "Download CV",
    "hero.title": "AI Engineering & Data Science",
    "hero.description": "Fourth-year computer engineering student at EMSI Casablanca, specializing in Data Science and Artificial Intelligence. Currently seeking a PFA internship in Data Analysis or Data Science.",
    "hero.location": "Sidi Ma'rouf, Casablanca, Morocco",
    "hero.download": "Download CV",
    "hero.projects": "View my projects",
    "hero.scroll": "Scroll to discover",
    "about.title": "About me",
    "about.subtitle": "Discover my background and motivation",
    "about.p1": "I am Yassine WALID, a passionate computer engineering student at EMSI Casablanca, currently in the fourth year of my engineering program. I specialize in Data Science and Artificial Intelligence, two fields shaping the future of technology.",
    "about.p2": "Single, 23 years old, and based in Sidi Ma'rouf, Casablanca, I am an aspiring professional who combines a strong theoretical foundation with hands-on experience. My journey has helped me master modern technologies and agile methodologies.",
    "about.p3": "In July 2025, I completed a one-month internship as a Full Stack Developer at xHub, in Casablanca Technopark. During this experience, I contributed to the development of the X-Bank digital banking platform, working on robust Spring Boot REST APIs and reactive React and TypeScript interfaces.",
    "about.p4": "I am currently looking for a PFA internship in Data Analysis or Data Science to deepen my skills and contribute to impactful projects. I am motivated by complex challenges and continuous learning.",
    "about.stats.study": "Years of study",
    "about.stats.projects": "Completed projects",
    "about.stats.languages": "Languages spoken",
    "about.stats.technologies": "Technologies mastered",
    "skills.title": "Skills",
    "skills.subtitle": "Proficiency in modern technologies across Data Science, development, and engineering",
    "skills.category.databases": "Databases",
    "skills.category.development": "Development",
    "skills.category.tools": "Tools & Platforms",
    "skills.additional": "Additional skills",
    "skills.advancedSql": "Advanced SQL",
    "skills.dataEngineering": "Data Engineering",
    "skills.dataCleaning": "Data Cleaning",
    "skills.cloud": "Cloud Computing",
    "skills.api": "RESTful APIs",
    "skills.agile": "Agile/Scrum",
    "projects.title": "Projects",
    "projects.subtitle": "Explore my projects in Data Science, full-stack development, and engineering",
    "projects.featured": "Featured project",
    "projects.featuredDescription": "Full-stack banking application with Spring Boot REST APIs and React/TypeScript interfaces. Includes announcement management, uploads, JWT authentication, admin dashboards, and analytics.",
    "projects.code": "View code",
    "projects.demo": "Demo",
    "projects.recent": "Recent projects",
    "projects.error": "Unable to load GitHub projects",
    "projects.noDescription": "No description",
    "projects.none": "No projects found",
    "projects.viewAll": "View all projects on GitHub",
    "timeline.title": "Education & Experience",
    "timeline.subtitle": "Academic and professional background",
    "timeline.experience": "Experience",
    "timeline.education": "Education",
    "timeline.internship.title": "Full Stack Developer Intern",
    "timeline.internship.period": "Jul. 2025 (1 month – Remote)",
    "timeline.internship.d1": "Developed RESTful APIs with Spring Boot for announcements, uploads, and JWT authentication",
    "timeline.internship.d2": "Created React/TypeScript interfaces for admin dashboards and analytics",
    "timeline.internship.d3": "Stack: Spring Boot, React, TypeScript, Java, PostgreSQL, JWT, Tailwind CSS",
    "timeline.engineering.title": "Engineering Program – Computer Science & Networks",
    "timeline.engineering.period": "2022–2027 (4th year)",
    "timeline.engineering.d1": "Specialization in Data Science and Artificial Intelligence",
    "timeline.engineering.d2": "Key courses: Databases, Statistics, Python/Java, AI, Big Data, NoSQL, Linux",
    "timeline.engineering.d3": "Actively seeking a PFA internship in Data Analysis or Data Science",
    "timeline.baccalaureate.title": "Physical Sciences Baccalaureate",
    "timeline.baccalaureate.period": "2019/2020",
    "timeline.baccalaureate.d1": "General education in physical sciences and mathematics",
    "location.casablanca": "Casablanca, Morocco",
    "languages.title": "Languages",
    "languages.subtitle": "Proficiency in several languages for effective communication",
    "languages.proficiency": "Proficiency",
    "languages.arabic": "Arabic",
    "languages.french": "French",
    "languages.english": "English",
    "languages.native": "Native",
    "languages.fluent": "Fluent",
    "languages.professional": "Professional",
    "interests.title": "Interests",
    "interests.gamingTitle": "Gaming",
    "interests.aiTitle": "Artificial Intelligence",
    "interests.travelTitle": "Travel",
    "interests.gaming": "Passion for video games and strategy",
    "interests.ai": "Fascination with AI and machine learning",
    "interests.travel": "Discovering new cultures and horizons",
    "contact.title": "Contact",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.location": "Location",
    "contact.subtitle": "Have an internship opportunity or a question? Feel free to get in touch.",
    "contact.information": "Contact information",
    "contact.social": "Social networks",
    "contact.send": "Send a message",
    "contact.fullName": "Full name",
    "contact.namePlaceholder": "Your name",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "Subject of your message",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Your message...",
    "contact.submit": "Send message",
    "contact.sending": "Opening Gmail...",
    "contact.validation.required": "Please fill in all fields",
    "contact.validation.email": "Please enter a valid email address",
    "contact.gmailNote": "This form opens a pre-filled Gmail compose window.",
    "contact.success": "Your message is ready in Gmail.",
    "contact.error": "Unable to open Gmail. Please try again.",
    "footer.navigation": "Navigation",
    "footer.social": "Social networks",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.in": "in Morocco",
  },
  fr: {
    "language.label": "Langue",
    "language.select": "Choisir la langue",
    "language.en": "English",
    "language.fr": "Français",
    "language.ar": "العربية",
    "theme.switchToDark": "Activer le mode sombre",
    "theme.switchToLight": "Activer le mode clair",
    "brand.role": "Ingénieur AI & Data Science",
    "nav.about": "À propos",
    "nav.skills": "Compétences",
    "nav.projects": "Projets",
    "nav.education": "Formation",
    "nav.contact": "Contact",
    "header.download": "Télécharger le CV",
    "hero.title": "Ingénierie AI & Data Science",
    "hero.description": "Étudiant en 4ème année d'ingénierie informatique à EMSI Casablanca, spécialisé en Data Science et Intelligence Artificielle. À la recherche d'un stage PFA en Data Analysis ou Data Science.",
    "hero.location": "Sidi Ma'rouf, Casablanca, Maroc",
    "hero.download": "Télécharger le CV",
    "hero.projects": "Voir mes projets",
    "hero.scroll": "Défiler pour découvrir",
    "about.title": "À propos",
    "about.subtitle": "Découvrez mon parcours et mes motivations",
    "about.p1": "Je suis Yassine WALID, un étudiant passionné en ingénierie informatique à EMSI Casablanca, actuellement en 4ème année de mon cycle d'ingénieur. Ma spécialisation porte sur la Data Science et l'Intelligence Artificielle, deux domaines qui façonnent l'avenir de la technologie.",
    "about.p2": "Célibataire, 23 ans, basé à Sidi Ma'rouf à Casablanca, je suis un professionnel en herbe qui combine une solide formation théorique avec une expérience pratique concrète. Mon parcours m'a permis de maîtriser les technologies modernes et les méthodologies agiles.",
    "about.p3": "En juillet 2025, j'ai complété un stage de 1 mois en tant que Full Stack Developer chez xHub, au Technopark de Casablanca. Pendant cette expérience, j'ai contribué au développement de la plateforme bancaire numérique X-Bank, en travaillant sur des APIs RESTful robustes avec Spring Boot et des interfaces réactives avec React et TypeScript.",
    "about.p4": "Actuellement, je recherche un stage PFA (Projet de Fin d'Année) en Data Analysis ou Data Science pour approfondir mes compétences et contribuer à des projets d'impact. Je suis motivé par les défis complexes et l'apprentissage continu.",
    "about.stats.study": "Années d'étude",
    "about.stats.projects": "Projets complétés",
    "about.stats.languages": "Langues parlées",
    "about.stats.technologies": "Technologies maîtrisées",
    "skills.title": "Compétences",
    "skills.subtitle": "Maîtrise des technologies modernes en Data Science, développement et ingénierie",
    "skills.category.databases": "Bases de données",
    "skills.category.development": "Développement",
    "skills.category.tools": "Outils & Plateformes",
    "skills.additional": "Compétences supplémentaires",
    "skills.advancedSql": "SQL avancé",
    "skills.dataEngineering": "Data Engineering",
    "skills.dataCleaning": "Nettoyage des données",
    "skills.cloud": "Cloud Computing",
    "skills.api": "APIs RESTful",
    "skills.agile": "Agile/Scrum",
    "projects.title": "Projets",
    "projects.subtitle": "Découvrez mes projets en Data Science, développement fullstack et ingénierie",
    "projects.featured": "Projet en vedette",
    "projects.featuredDescription": "Application bancaire fullstack avec APIs RESTful Spring Boot et interfaces React/TypeScript. Gestion des annonces, uploads, authentification JWT, dashboards admin et analytics.",
    "projects.code": "Voir le code",
    "projects.demo": "Démo",
    "projects.recent": "Projets récents",
    "projects.error": "Impossible de charger les projets GitHub",
    "projects.noDescription": "Pas de description",
    "projects.none": "Aucun projet trouvé",
    "projects.viewAll": "Voir tous les projets sur GitHub",
    "timeline.title": "Formation & Expérience",
    "timeline.subtitle": "Parcours académique et professionnel",
    "timeline.experience": "Expérience",
    "timeline.education": "Formation",
    "timeline.internship.title": "Stagiaire Full Stack Developer",
    "timeline.internship.period": "Juil. 2025 (1 mois – Remote)",
    "timeline.internship.d1": "Développement d'APIs RESTful avec Spring Boot pour la gestion des annonces, uploads et authentification JWT",
    "timeline.internship.d2": "Création d'interfaces React/TypeScript pour dashboards admin et analytics",
    "timeline.internship.d3": "Stack: Spring Boot, React, TypeScript, Java, PostgreSQL, JWT, Tailwind CSS",
    "timeline.engineering.title": "Cycle Ingénieur – Informatique et Réseaux",
    "timeline.engineering.period": "2022–2027 (4ème année)",
    "timeline.engineering.d1": "Spécialisation en Data Science et Intelligence Artificielle",
    "timeline.engineering.d2": "Cours clés: Bases de données, Statistiques, Python/Java, IA, Big Data, NoSQL, Linux",
    "timeline.engineering.d3": "Recherche active d'un stage PFA en Data Analysis / Data Science",
    "timeline.baccalaureate.title": "Baccalauréat Sciences Physiques",
    "timeline.baccalaureate.period": "2019/2020",
    "timeline.baccalaureate.d1": "Formation générale en sciences physiques et mathématiques",
    "location.casablanca": "Casablanca, Maroc",
    "languages.title": "Langues",
    "languages.subtitle": "Maîtrise de plusieurs langues pour une communication efficace",
    "languages.proficiency": "Niveau",
    "languages.arabic": "Arabe",
    "languages.french": "Français",
    "languages.english": "Anglais",
    "languages.native": "Langue maternelle",
    "languages.fluent": "Courant",
    "languages.professional": "Professionnel",
    "interests.title": "Centres d'intérêt",
    "interests.gamingTitle": "Gaming",
    "interests.aiTitle": "Intelligence Artificielle",
    "interests.travelTitle": "Voyage",
    "interests.gaming": "Passion pour les jeux vidéo et la stratégie",
    "interests.ai": "Fascination pour l'IA et le machine learning",
    "interests.travel": "Découverte de nouvelles cultures et horizons",
    "contact.title": "Contact",
    "contact.email": "Email",
    "contact.phone": "Téléphone",
    "contact.location": "Localisation",
    "contact.subtitle": "Vous avez une opportunité de stage ou une question ? N'hésitez pas à me contacter.",
    "contact.information": "Informations",
    "contact.social": "Réseaux sociaux",
    "contact.send": "Envoyer un message",
    "contact.fullName": "Nom complet",
    "contact.namePlaceholder": "Votre nom",
    "contact.emailPlaceholder": "votre.email@example.com",
    "contact.subject": "Sujet",
    "contact.subjectPlaceholder": "Objet de votre message",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Votre message...",
    "contact.submit": "Envoyer le message",
    "contact.sending": "Ouverture de Gmail...",
    "contact.validation.required": "Veuillez remplir tous les champs",
    "contact.validation.email": "Veuillez entrer une adresse email valide",
    "contact.gmailNote": "Ce formulaire ouvre une fenêtre Gmail préremplie.",
    "contact.success": "Votre message est prêt dans Gmail.",
    "contact.error": "Impossible d'ouvrir Gmail. Veuillez réessayer.",
    "footer.navigation": "Navigation",
    "footer.social": "Réseaux sociaux",
    "footer.rights": "Tous droits réservés.",
    "footer.madeWith": "Fait avec",
    "footer.in": "au Maroc",
  },
  ar: {
    "language.label": "اللغة",
    "language.select": "اختر اللغة",
    "language.en": "English",
    "language.fr": "Français",
    "language.ar": "العربية",
    "theme.switchToDark": "تفعيل الوضع الداكن",
    "theme.switchToLight": "تفعيل الوضع الفاتح",
    "brand.role": "مهندس الذكاء الاصطناعي وعلوم البيانات",
    "nav.about": "نبذة عني",
    "nav.skills": "المهارات",
    "nav.projects": "المشاريع",
    "nav.education": "التعليم",
    "nav.contact": "تواصل معي",
    "header.download": "تحميل السيرة الذاتية",
    "hero.title": "هندسة الذكاء الاصطناعي وعلوم البيانات",
    "hero.description": "طالب في السنة الرابعة هندسة معلوماتية في EMSI الدار البيضاء، متخصص في علوم البيانات والذكاء الاصطناعي. أبحث حاليًا عن تدريب PFA في تحليل البيانات أو علوم البيانات.",
    "hero.location": "سيدي معروف، الدار البيضاء، المغرب",
    "hero.download": "تحميل السيرة الذاتية",
    "hero.projects": "استعرض مشاريعي",
    "hero.scroll": "مرر لاكتشاف المزيد",
    "about.title": "نبذة عني",
    "about.subtitle": "اكتشف مساري ودوافعي",
    "about.p1": "أنا ياسين وليد، طالب شغوف في هندسة المعلوماتية في EMSI الدار البيضاء، وأدرس حاليًا في السنة الرابعة من مساري الهندسي. أختص في علوم البيانات والذكاء الاصطناعي، وهما مجالان يصنعان مستقبل التكنولوجيا.",
    "about.p2": "أبلغ من العمر 23 سنة وأقيم في سيدي معروف بالدار البيضاء. أنا مهندس مستقبلي أجمع بين تكوين نظري قوي وتجربة عملية ملموسة، وقد ساعدني مساري على إتقان التقنيات الحديثة والمنهجيات الرشيقة.",
    "about.p3": "في يوليوز 2025، أنجزت تدريبًا لمدة شهر واحد كمطور Full Stack لدى xHub في تكنوبارك الدار البيضاء. ساهمت خلال هذه التجربة في تطوير منصة X-Bank البنكية الرقمية، من خلال العمل على REST APIs قوية باستخدام Spring Boot وواجهات React وTypeScript تفاعلية.",
    "about.p4": "أبحث حاليًا عن تدريب PFA في تحليل البيانات أو علوم البيانات لتعميق مهاراتي والمساهمة في مشاريع ذات أثر. تحفزني التحديات المعقدة والتعلم المستمر.",
    "about.stats.study": "سنوات الدراسة",
    "about.stats.projects": "المشاريع المنجزة",
    "about.stats.languages": "اللغات المتحدث بها",
    "about.stats.technologies": "التقنيات المتقنة",
    "skills.title": "المهارات",
    "skills.subtitle": "إتقان التقنيات الحديثة في علوم البيانات والتطوير والهندسة",
    "skills.category.databases": "قواعد البيانات",
    "skills.category.development": "التطوير",
    "skills.category.tools": "الأدوات والمنصات",
    "skills.additional": "مهارات إضافية",
    "skills.advancedSql": "SQL متقدم",
    "skills.dataEngineering": "هندسة البيانات",
    "skills.dataCleaning": "تنظيف البيانات",
    "skills.cloud": "الحوسبة السحابية",
    "skills.api": "RESTful APIs",
    "skills.agile": "Agile/Scrum",
    "projects.title": "المشاريع",
    "projects.subtitle": "اكتشف مشاريعي في علوم البيانات والتطوير الكامل والهندسة",
    "projects.featured": "مشروع مميز",
    "projects.featuredDescription": "تطبيق مصرفي Full Stack بواجهات Spring Boot REST وواجهات React/TypeScript. يتضمن إدارة الإعلانات والتحميلات ومصادقة JWT ولوحات تحكم للمشرف وتحليلات.",
    "projects.code": "عرض الكود",
    "projects.demo": "عرض تجريبي",
    "projects.recent": "المشاريع الأخيرة",
    "projects.error": "تعذر تحميل مشاريع GitHub",
    "projects.noDescription": "لا يوجد وصف",
    "projects.none": "لم يتم العثور على مشاريع",
    "projects.viewAll": "عرض جميع المشاريع على GitHub",
    "timeline.title": "التعليم والخبرة",
    "timeline.subtitle": "المسار الأكاديمي والمهني",
    "timeline.experience": "الخبرة",
    "timeline.education": "التعليم",
    "timeline.internship.title": "متدرب Full Stack Developer",
    "timeline.internship.period": "يوليوز 2025 (شهر واحد – عن بعد)",
    "timeline.internship.d1": "تطوير RESTful APIs باستخدام Spring Boot لإدارة الإعلانات والتحميلات ومصادقة JWT",
    "timeline.internship.d2": "إنشاء واجهات React/TypeScript للوحات تحكم المشرف والتحليلات",
    "timeline.internship.d3": "التقنيات: Spring Boot وReact وTypeScript وJava وPostgreSQL وJWT وTailwind CSS",
    "timeline.engineering.title": "مسار الهندسة – المعلوميات والشبكات",
    "timeline.engineering.period": "2022–2027 (السنة الرابعة)",
    "timeline.engineering.d1": "تخصص في علوم البيانات والذكاء الاصطناعي",
    "timeline.engineering.d2": "المواد الأساسية: قواعد البيانات والإحصاء وPython/Java والذكاء الاصطناعي والبيانات الضخمة وNoSQL وLinux",
    "timeline.engineering.d3": "أبحث بنشاط عن تدريب PFA في تحليل البيانات أو علوم البيانات",
    "timeline.baccalaureate.title": "بكالوريا العلوم الفيزيائية",
    "timeline.baccalaureate.period": "2019/2020",
    "timeline.baccalaureate.d1": "تكوين عام في العلوم الفيزيائية والرياضيات",
    "location.casablanca": "الدار البيضاء، المغرب",
    "languages.title": "اللغات",
    "languages.subtitle": "إتقان عدة لغات من أجل تواصل فعال",
    "languages.proficiency": "المستوى",
    "languages.arabic": "العربية",
    "languages.french": "الفرنسية",
    "languages.english": "الإنجليزية",
    "languages.native": "اللغة الأم",
    "languages.fluent": "بطلاقة",
    "languages.professional": "مستوى مهني",
    "interests.title": "الاهتمامات",
    "interests.gamingTitle": "الألعاب",
    "interests.aiTitle": "الذكاء الاصطناعي",
    "interests.travelTitle": "السفر",
    "interests.gaming": "شغف بألعاب الفيديو والاستراتيجية",
    "interests.ai": "اهتمام بالذكاء الاصطناعي وتعلم الآلة",
    "interests.travel": "اكتشاف ثقافات وآفاق جديدة",
    "contact.title": "تواصل معي",
    "contact.email": "البريد الإلكتروني",
    "contact.phone": "الهاتف",
    "contact.location": "الموقع",
    "contact.subtitle": "هل لديك فرصة تدريب أو سؤال؟ لا تتردد في التواصل معي.",
    "contact.information": "معلومات التواصل",
    "contact.social": "الشبكات الاجتماعية",
    "contact.send": "إرسال رسالة",
    "contact.fullName": "الاسم الكامل",
    "contact.namePlaceholder": "اسمك",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.subject": "الموضوع",
    "contact.subjectPlaceholder": "موضوع رسالتك",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "رسالتك...",
    "contact.submit": "إرسال الرسالة",
    "contact.sending": "فتح Gmail...",
    "contact.validation.required": "يرجى ملء جميع الحقول",
    "contact.validation.email": "يرجى إدخال بريد إلكتروني صالح",
    "contact.gmailNote": "سيفتح هذا النموذج نافذة إنشاء رسالة Gmail مملوءة مسبقًا.",
    "contact.success": "رسالتك جاهزة في Gmail.",
    "contact.error": "تعذر فتح Gmail. يرجى المحاولة مرة أخرى.",
    "footer.navigation": "التنقل",
    "footer.social": "الشبكات الاجتماعية",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.madeWith": "صُنع بـ",
    "footer.in": "في المغرب",
  },
};

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
  languageOptions: Array<{ value: Locale; label: string }>;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem("portfolio-locale");
    return stored === "fr" || stored === "ar" || stored === "en" ? stored : "en";
  });

  useEffect(() => {
    const root = document.documentElement;
    root.lang = locale;
    root.dir = locale === "ar" ? "rtl" : "ltr";
    window.localStorage.setItem("portfolio-locale", locale);
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale,
    t: (key: string) => translations[locale][key] ?? translations.en[key] ?? key,
    languageOptions: [
      { value: "en", label: translations[locale]["language.en"] },
      { value: "fr", label: translations[locale]["language.fr"] },
      { value: "ar", label: translations[locale]["language.ar"] },
    ],
  }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
